steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tvguide:${SHORT_SHA}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/tvguide"]

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'tvguide-standard', '--image', 'gcr.io/$PROJECT_ID/tvguide:${SHORT_SHA}', '--region', 'europe-west1']